steps:

- id: 'tag name'
  name: 'alpine'
  entrypoint: 'sh'
  args:
  - '-c'
  - |
      echo "***********************"
      echo "$TAG_NAME"
      echo "***********************"

- id: 'Clone repo with TAG'
  name: 'gcr.io/cloud-builders/git'
  args:
  - clone
  - --branch
  - $TAG_NAME
  - 'https://github.com/emoronayuso/pubsub-subscriber.git'
  dir: '.'

- id: 'gcloud functions deploy'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - functions
  - deploy
  - subscriber_cf
  - --region=europe-west3
  - --source=.
  - --trigger-topic=topic-cf
  - --runtime=python39
  - --service-account=sa-subscription@pruebas-pubsub-systerminal.iam.gserviceaccount.com
  - --allow-unauthenticated
  - --docker-repository=projects/pruebas-pubsub-systerminal/locations/europe-west3/repositories/subscriber-cf-rep

- id: 'gcloud functions set label artifact'
  name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  args:
  - gcloud
  - artifacts
  - docker
  - tags
  - add
  - europe-west3-docker.pkg.dev/pruebas-pubsub-systerminal/subscriber-cf-rep/subscriber__cf:latest
  - europe-west3-docker.pkg.dev/pruebas-pubsub-systerminal/subscriber-cf-rep/subscriber__cf:$TAG_NAME
