steps:

- id: 'tag name'
  name: 'alpine'
  entrypoint: 'sh'  
  args: 
  - '-c'
  - | 
      echo "***********************"
      echo "$TAG_NAME"
      echo "***********************"

- id: 'gcloud functions deploy'
  name: gcr.io/cloud-builders/gcloud
  entrypoint: 'sh'
  args: 
    - '-c'
    - >
      gcloud projects list
